#! /bin/sh

bspc config border_width        1
bspc config window_gap          22

bspc config split_ratio         0.6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# Color
#bspc config active_border_color Gainsboro
#bspc config normal_border_color Gainsboro
#bspc config focused_border_color White

# Mouse gives focus, mouse follows monitor
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# List of named monitors
bspc monitor -d 0 1 2 3 4

# Gimp on desktop 8
bspc rule -a Gimp desktop=^4 follow=on floating=on
