#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap          27

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true

# Coloro
bspc config normal_border_color  '#2d2f31'
bspc config focused_border_color '#d5d8d6'

# Mouse gives focus, mouse follows monitor
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# List of named monitors
bspc monitor -d 1 2 3 4 5
