#! /bin/sh

bspc config border_width        1
bspc config window_gap          14

bspc config split_ratio         0.55
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# Color
bspc config active_border_color $(getcolor 8)
bspc config normal_border_color $(getcolor 7)
bspc config focused_border_color $(getcolor 1)

# Mouse gives focus, mouse follows monitor
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# Lol wut?
bspc monitor -d 0 1 2 3 4

# Gimp on desktop 8
bspc rule -a Gimp desktop=^4 follow=on floating=on
